# Voorspellingenblad {#app-voorspellingenblad}

In het standaard Voorspellingblad (ook wel Prognosewerkblad) zijn een tweetal keuzes te maken:

+ *Grafiektype* - lijndiagram of kolomdiagram  via de twee pictogrammen rechtsboven.
+ *Einde van prognose*- de einddatum voor de prognose, dus het aantal prognoses (linksonder)

Via de selectieknop **Opties** (linksonder) heb je nog een aantal mogelijkheden:

De verschillende mogelijkheden worden hierna toegelicht.

**Start van prognose**

De begindatum voor de prognose wordt automatisch door Excel geselecteerd. Je kunt deze wijzigen. Wanneer je een datum kiest vóór het einde van de historische gegevens, worden alleen gegevens vóór de begindatum gebruikt in de voorspelling (dit wordt soms ook wel *backcasting* genoemd).

::: {.tip}
+ Als je de prognose start vóór het laatste historische punt, krijg je een goed beeld van de nauwkeurigheid van de voorspelling, omdat je de voorspelde reeks kunt vergelijken met de werkelijke gegevens. Als je de prognose echter te vroeg start, is de gegenereerde prognose mogelijk niet hetzelfde als de prognose die je krijgt wanneer je alle historische gegevens gebruikt. De voorspelling wordt nauwkeuriger als je alle historische gegevens gebruikt.

+ Als de gegevens seizoensgebonden zijn, kun je het beste een prognose starten vóór het laatste historische punt.
:::

**Betrouwbaarheidsinterval**

Hier kun je het weergeven van een betrouwbaarheidsinterval in of uit schakelen. Hiermee kun je de nauwkeurigheid van de voorspelling vaststellen. Een kleiner interval betekent een betrouwbaardere voorspelling voor het specifieke punt. Standaard is het een 95% betrouwbaarheidsinterval dat gewijzigd kan worden.

**Seizoensgebonden**

Wanneer het patroon van de gegevens een seizoensgebondenheid bevat dan kun je hier het aantal waarnemingen voor het patroon instellen. Standaard is automatisch detecteren ingesteld, waardoor Excel via een algoritme automatisch het aantal tijdsperioden van het seizoenspatroon vaststelt. Je kunt het beste via de optie Handmatig zelf de lengte van het seizoenspatroon ingeven en de mogelijkheid voor automatische detectie alleen gebruiken om jouw vermoeden over de lengte te laten bevestigen.

**Bereik van de tijdlijn**

Hiermee kun je het bereik voor de kolom met tijdgegevens instellen. Dit bereik moet hetzelfde zijn als het Bereik van waarden.

**Bereik van waarden**

Hiermee kun je het bereik voor de kolom met waarden instellen. Dit bereik moet hetzelfde zijn als het Bereik van de tijdlijn. 

**Ontbrekende punten invullen met**

Wanneer in de gegevensverzameling ontbrekende waarden voorkomen, dan vult Excel deze zelf in op basis van interpolatie. Dit houdt in dat een ontbrekend punt wordt ingevuld als het gewogen gemiddelde van de aangrenzende punten mits er minder dan 30% van de punten ontbreekt. Als je in plaats hiervan de ontbrekende waarden als nullen wilt behandelen, dan selecteer je "Nullen" in de lijst.

**Duplicaten samenvoegen met**

Wanneer de gegevens meerdere waarden met de dezelfde tijdstempel bevatten, dan neemt Excel hiervoor het gemiddelde van deze waarden. Als je een andere berekeningsmethode wilt gebruiken, dan kun je in de lijst kiezen uit: Gemiddelde, Aantal, AantalArg, Max, Mediaan, Min en Som.

**Prognose van statistieken opnemen**

Via dit selectievakje kun je aanvullende statistische informatie over de prognose in het voorspellingblad laten opnemen. Met behulp van de functie `VOORSPELLEN.ETS.STAT` wordt een tabel met statistieken gegenereerd.
