# (APPENDIX) Bijlagen {-}

# Addin Gegevensanalyse {#app-toolpak}

Gegevensanalyse (Engels: Data Analysis Toolpak) is een hulpprogramma voor het uitvoeren van analyses. Het wordt standaard met Excel meegeleverd, maar is niet altijd geactiveerd. Om dit te controleren kies je tabblad Gegevens en kijk je in de groep Analyse of daar het onderdeel Gegevensanalyse staat. Zoniet, dan kun je het onderdeel als volgt activeren.

1. Kies *Tab Bestand \> Opties \> categorie Invoegtoepassingen*.
2. Selecteer in het vak *Beheren* de optie *Excel-invoegtoepassingen* en klik op *Start*.
3. Selecteer in het vak *Invoegtoepassinge*n het selectievakje *Analysis ToolPak*. Je hoeft *Analysis ToolPak - VBA* niet te installeren,
4. Klik op *OK*. Wanneer je nu op de *tab Gegevens* klikt zie je aan de rechterkant de knop *Gegevensanalyse (groep Analyse)*.

::: {.important}
+ Als Analysis ToolPak niet voorkomt in het vak *Beschikbare invoegtoepassinge*n, klik je op *Bladeren* om naar de invoegtoepassing te zoeken.
+ Als je het bericht krijgt dat Analysis ToolPak niet is geïnstalleerd op jouw computer, klik je op *Ja* om de invoegtoepassing te installeren.
:::

Om het hulpprogramma te gebruiken kies je *tab Gegevens \> Gegevensanalyse (groep Analyse)*. Je kunt daarna kiezen uit de volgende functies (in alfabetische volgorde). Een aantal van deze functies zullen in de desbetreffende hoofdstukken verder toegelicht worden.

+ **Aselecte getallen** - Voor het vullen van een bereik met willekeurige getallen uit een van de bekende theoretische kansverdelingen. Zie verder \@ref(app-aselect).
+ **Beschrijvende statistiek** - Voor het genereren van een statistisch rapport van gegevens, waaronder informatie over het centrum en de spreiding van de gegevens. Wordt gebruikt in \@ref(beschrijvend)
+ **Correlatie** - Voor het bepalen van de correlatiecoëfficient tussen twee variabelen. Wordt gebruikt in hoofdstuk \@ref(linregressie).
+ **Covariantie** - Voor het bepalen van de correlatiecoëfficient tussen twee variabelen. Zie ook hoofdstuk \@ref(linregressie).
+ **Exponentiële demping** - Voor het analyseren van tijdreeksen via exponentiële demping. Zie ook hoofdstuk \@ref(timeseries).
+ **Fourier-analyse** - Voor het oplossen van vraagstukken in lineaire systemen.
+ **Histogram** - Voor het bepalen van frequenties en het tekenen van een bijbehorend histogram.
+ **F-toets voor twee steekproeven** - Voor het uitvoeren van een F-toets om na te gaan of de varianties van twee normale verdelingen verschillen..
+ **Multifactoriële variantie-analyse met herhaling** - Voor het uitvoeren van een variantieanalyse waarbij er voor elke groep herhaalde waarnemingen zijn.
+ **Multifactoriële variantie-analyse zonder herhaling** - Voor het uitvoeren van een variantieanalyse waarbij voor elk paar nu één waarneming is. 
+ **Rang en percentiel** - Voor het genereren van een tabel met rangordes en percentielwaarden.
+ **Regressie** - Voor het uitvoeren van een lineaire regressieanalyse. Wordt gebruikt in hoofdstuk \@ref(linregressie).
+ **Steekproef** - Voor het trekken van een steekproef uit een populatie, desgewenst ook voor seizoensafhankelijke gegevens.
+ **T-toets: twee gepaarde steekproeven met gelijke varianties** - Voor het toetsen of de populatiegemiddelden van twee steekproeven (met gelijke varianties) hetzelfde zijn. Ook wel homoscedastische T-toets genoemd.
+ **T-toets: twee gepaarde steekproeven voor gemiddelden** - Voor het toetsen of de populatiegemiddelden van twee gepaarde steekproeven hetzelfde zijn.
+ **T-toets: twee steekproeven met ongelijke varianties** - Voor het toetsen of de populatiegemiddelden van twee steekproeven (met ongelijke varianties) hetzelfde zijn. Ook wel heteroscedastische T-toets genoemd.
+ **Unifactoriële variantie-analyse** - Voor het uitvoeren van een variantie-analyse op gegevens van twee of meer steekproeven. Getoetst wordt of elke steekproef al dan niet getrokken is uit dezelfde onderliggende kansverdeling. Bij twee steekproeven kun je ook de *T-Toets* gebruiken.
+ **Z-toets: twee steekproeven voor gemiddelden** - Voor het uitvoeren van een Z-toets om te bepalen of de gemiddelden van twee steekproeven met bekende varianties al dan niet van elkaar verschillen.
+ **Zwevend gemiddelde** - Voor het bepalen van een voortschrijdend gemiddelde over een bepaald aantal waarden in voorafgaande perioden. Wordt gebruikt in hoofdstuk \@ref(timeseries).

